Лабораторна робота № 8
Смислов Даніл
ІП-01

Спочатку імпортуємо потрібні для роботи бібліотеки

In [1]:
import pandas as pd 
import numpy as np

In [2]:
def getDataset():
    data = pd.read_csv('data/text.csv',sep=',',encoding='utf-8')
    return data 

dataset = getDataset()
dataset.info()
dataset.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      1122 non-null   object
 1   Title   1122 non-null   object
 2   Body    1122 non-null   object
dtypes: object(3)
memory usage: 26.4+ KB

,Id,Title,Body
0,http://k.img.com.ua/rss/ua/4013798,Кличко покликав німецьких інвесторів до Києва,Київ - перспективний і відкритий ринок для біз...
1,http://k.img.com.ua/rss/ua/4001679,"З'явилося відео, як байкер почав стріляти у во...",З'явилося відео конфлікту між мотоциклістом...
2,http://k.img.com.ua/rss/ua/4001390,У центрі Києва посеред вулиці помер чоловік,У Києві на Бессарабській площі вранці в четвер...
3,http://k.img.com.ua/rss/ua/4001239,Нічний ураган перетворив Хрещатик на смітник,Київ вночі 16 серпня пережив найсильнішу грозу...
4,http://k.img.com.ua/rss/ua/4001227,Потоп у Києві: столицю накрив ураган з градом,Уночі Київ вкотре накрила негода. Найсильніший...
5,http://k.img.com.ua/rss/ua/4001167,У Києві потрапив в ДТП екс-нардеп Мірошниченко,Колишній народний депутат від партії Свобода І...
6,http://k.img.com.ua/rss/ua/3999827,У Києві пограбували ювелірний магазин і застре...,У Києві троє невідомих пограбували ювелірний м...
7,http://k.img.com.ua/rss/ua/3999524,У Києві обмежать рух Північним мостом,"У Києві на вихідних, 11-12 серпня, буде обмеже..."
8,http://k.img.com.ua/rss/ua/3999429,"У Києві ""замінували"" майдан Незалежності",На майдані Незалежності в Києві шукають вибухі...
9,http://k.img.com.ua/rss/ua/3999418,У Києві посилять заходи безпеки 10 і 12 серпня,У Києві у зв'язку з проведенням футбольних мат...

Давайте очистимо наші дані від тегів та розмітки, використаємо регулярні вирази. Також приведемо до нижнього регістру.

In [3]:
import re

columns = ["Title","Body"]

def clearText(column):
    for i in range(0,1122):    
        dataset.loc[i][column] = re.sub(r"<[^>]+>", "", dataset.loc[i][column])
        dataset.loc[i][column] = re.sub('[^A-Za-zА-Яа-яҐґЄєІіЇї\']+', " ", dataset.loc[i][column])
        dataset.loc[i][column] = dataset.loc[i][column].lower()
clearText("Title")
clearText("Body")

In [4]:
dataset.info()
dataset.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      1122 non-null   object
 1   Title   1122 non-null   object
 2   Body    1122 non-null   object
dtypes: object(3)
memory usage: 26.4+ KB

,Id,Title,Body
0,http://k.img.com.ua/rss/ua/4013798,кличко покликав німецьких інвесторів до києва,київ перспективний і відкритий ринок для бізне...
1,http://k.img.com.ua/rss/ua/4001679,з'явилося відео як байкер почав стріляти у вод...,з'явилося відео конфлікту між мотоциклістом і...
2,http://k.img.com.ua/rss/ua/4001390,у центрі києва посеред вулиці помер чоловік,у києві на бессарабській площі вранці в четвер...
3,http://k.img.com.ua/rss/ua/4001239,нічний ураган перетворив хрещатик на смітник,київ вночі серпня пережив найсильнішу грозу зі...
4,http://k.img.com.ua/rss/ua/4001227,потоп у києві столицю накрив ураган з градом,уночі київ вкотре накрила негода найсильніший ...
5,http://k.img.com.ua/rss/ua/4001167,у києві потрапив в дтп екс нардеп мірошниченко,колишній народний депутат від партії свобода і...
6,http://k.img.com.ua/rss/ua/3999827,у києві пограбували ювелірний магазин і застре...,у києві троє невідомих пограбували ювелірний м...
7,http://k.img.com.ua/rss/ua/3999524,у києві обмежать рух північним мостом,у києві на вихідних серпня буде обмежено рух н...
8,http://k.img.com.ua/rss/ua/3999429,у києві замінували майдан незалежності,на майдані незалежності в києві шукають вибухі...
9,http://k.img.com.ua/rss/ua/3999418,у києві посилять заходи безпеки і серпня,у києві у зв'язку з проведенням футбольних мат...

Давайте тепер зчитаємо стоп-слова, щоб потім не брати їх до аналізу.Також додамо свої стоп-слова, а саме різні абревіатури.

In [5]:
import csv
def getStop():
    stop = list()
    with open('data/stopWords.csv',encoding = 'utf-8') as stopCsv:
        reader = csv.reader(stopCsv,delimiter = ',')
        for row in reader:
            stop.append(row[0])
    return stop 

stop = getStop()

abbreviations = ['тис', 'млн', 'грн', 'т.я', 'вул', 'cек', 'хв', 'обл', 'кв', 'пл', 'напр', 'гл', 'і.о', 'зам']

for i in range(0,14):
    stop.append(abbreviations[i])

Давайте розіб'ємо текст на токени.

In [6]:
import nltk

tokens = nltk.tokenize.word_tokenize(dataset["Body"][0])
def tokenize(column):
    for i in range(0,1122):    
        tokens = nltk.word_tokenize(dataset.loc[i][column])
        tokens = [word for word in tokens if word not in stop]
        dataset[column].loc[i] = tokens
tokenize("Title")
tokenize("Body")


dataset.info()
dataset.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      1122 non-null   object
 1   Title   1122 non-null   object
 2   Body    1122 non-null   object
dtypes: object(3)
memory usage: 26.4+ KB

,Id,Title,Body
0,http://k.img.com.ua/rss/ua/4013798,"[кличко, покликав, німецьких, інвесторів, києва]","[київ, перспективний, відкритий, ринок, бізнес..."
1,http://k.img.com.ua/rss/ua/4001679,"[з'явилося, відео, байкер, почав, стріляти, во...","[з'явилося, відео, конфлікту, мотоциклістом, в..."
2,http://k.img.com.ua/rss/ua/4001390,"[центрі, києва, вулиці, помер, чоловік]","[києві, бессарабській, площі, вранці, четвер, ..."
3,http://k.img.com.ua/rss/ua/4001239,"[нічний, ураган, перетворив, хрещатик, смітник]","[київ, вночі, серпня, пережив, найсильнішу, гр..."
4,http://k.img.com.ua/rss/ua/4001227,"[потоп, києві, столицю, накрив, ураган, градом]","[уночі, київ, вкотре, накрила, негода, найсиль..."
5,http://k.img.com.ua/rss/ua/4001167,"[києві, потрапив, дтп, екс, нардеп, мірошниченко]","[колишній, народний, депутат, партії, свобода,..."
6,http://k.img.com.ua/rss/ua/3999827,"[києві, пограбували, ювелірний, магазин, застр...","[києві, троє, невідомих, пограбували, ювелірни..."
7,http://k.img.com.ua/rss/ua/3999524,"[києві, обмежать, рух, північним, мостом]","[києві, вихідних, серпня, обмежено, рух, півні..."
8,http://k.img.com.ua/rss/ua/3999429,"[києві, замінували, майдан, незалежності]","[майдані, незалежності, києві, шукають, вибухі..."
9,http://k.img.com.ua/rss/ua/3999418,"[києві, посилять, заходи, безпеки, серпня]","[києві, зв'язку, проведенням, футбольних, матч..."

Тепер давайте проведемо лематизацію.

In [7]:
import pymorphy2

morph = pymorphy2.MorphAnalyzer(lang='uk')
def lematization(column):
    for i in range(0,1122):    
        lems = []
        for word in dataset.loc[i][column]:
            lem = morph.parse(word)[0].normal_form
            lems.append(lem)
        dataset.loc[i][column] = lems
lematization("Title")
lematization("Body")


dataset.info()
dataset.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      1122 non-null   object
 1   Title   1122 non-null   object
 2   Body    1122 non-null   object
dtypes: object(3)
memory usage: 26.4+ KB

,Id,Title,Body
0,http://k.img.com.ua/rss/ua/4013798,"[кличко, покликати, німецький, інвестор, київ]","[кий, перспективний, відкритий, ринок, бізнес,..."
1,http://k.img.com.ua/rss/ua/4001679,"[з'явитися, відео, байкер, почати, стріляти, в...","[з'явитися, відео, конфлікт, мотоцикліст, воді..."
2,http://k.img.com.ua/rss/ua/4001390,"[центр, київ, вулиця, померти, чоловік]","[кий, бессарабський, площа, вранці, четвер, се..."
3,http://k.img.com.ua/rss/ua/4001239,"[нічний, ураган, перетворити, хрещатик, смітник]","[кий, вночі, серпень, пережити, найсильніший, ..."
4,http://k.img.com.ua/rss/ua/4001227,"[потоп, кий, столиця, накрити, ураган, град]","[уночі, кий, вкотре, накрити, негода, найсильн..."
5,http://k.img.com.ua/rss/ua/4001167,"[кий, потрапити, дтп, екс, нардеп, мірошниченко]","[колишній, народний, депутат, партія, свобода,..."
6,http://k.img.com.ua/rss/ua/3999827,"[кий, пограбувати, ювелірний, магазин, застрел...","[кий, троя, невідомий, пограбувати, ювелірний,..."
7,http://k.img.com.ua/rss/ua/3999524,"[кий, обмежити, рух, північний, міст]","[кий, вихідний, серпень, обмежити, рух, північ..."
8,http://k.img.com.ua/rss/ua/3999429,"[кий, замінувати, майдан, незалежність]","[майдан, незалежність, кий, шукати, вибухівка,..."
9,http://k.img.com.ua/rss/ua/3999418,"[кий, посилити, захід, безпека, серпень]","[кий, зв'язкий, проведення, футбольний, матч, ..."

Давайте напишемо функцію підрахунку кількостей слів в тексті.

In [8]:
def wordCount(words):
    counts = {}
    for word in words:
        if word not in counts.keys():
            counts[word] = 1
        else:
            counts[word] += 1
    return dict(sorted(counts.items(), reverse=True, key=lambda x: x[1]))
print(wordCount(dataset.loc[0]["Body"]))

{'кличко': 11, 'кий': 10, 'мер': 7, 'німецький': 7, 'місто': 6, 'інвестиція': 5, 'київ': 5, 'зазначити': 5, 'столиця': 5, 'перспективний': 4, 'ринок': 4, 'бізнес': 4, 'німеччина': 4, 'компанія': 4, 'український': 4, 'партнер': 4, 'україна': 4, 'відкритий': 3, 'віталій': 3, 'співпраця': 3, 'управління': 3, 'один': 3, 'європейський': 3, 'працювати': 3, 'робити': 3, 'економіка': 2, 'представник': 2, 'інвестор': 2, 'запевнити': 2, 'надійний': 2, 'хотіти': 2, 'розвиток': 2, 'основний': 2, 'підкреслити': 2, 'бюджет': 2, 'міський': 2, 'smart': 2, 'city': 2, 'фахівець': 2, 'рівня': 2, 'країна': 2, 'рівень': 2, 'заявити': 1, 'виступ': 1, 'дно': 1, 'цьогоріч': 1, 'проходити': 1, 'аахен': 1, 'інформувати': 1, 'прес': 1, 'служба': 1, 'четвер': 1, 'вересень': 1, 'головний': 1, 'тема': 1, 'форум': 1, 'світовий': 1, 'торгівля': 1, 'умова': 1, 'глобальний': 1, 'зміна': 1, 'він': 1, 'брати': 1, 'участь': 1, 'чоловік': 1, 'середа': 1, 'понад': 1, 'промислово': 1, 'торговельний': 1, 'палата': 1, 'провідний': 1, 'здійснювати': 1, 'зовнішньоторговельний': 1, 'діяльність': 1, 'експерт': 1, 'підготовлений': 1, 'інвестування': 1, 'іноземний': 1, 'приходити': 1, 'введений': 1, 'прозорий': 1, 'механізм': 1, 'гарант': 1, 'виступати': 1, 'особисто': 1, 'захисник': 1, 'говорити': 1, 'німецьки': 1, 'приречений': 1, 'ефективний': 1, 'налаштований': 1, 'звернутися': 1, 'пріоритетний': 1, 'напрямок': 1, 'відносини': 1, 'допомагати': 1, 'політично': 1, 'підтримувати': 1, 'прагнення': 1, 'зовнішньоекономічний': 1, 'відомий': 1, 'deutz': 1, 'fahr': 1, 'knauf': 1, 'hipp': 1, 'walter': 1, 'bau': 1, 'leon': 1, 'bmw': 1, 'man': 1, 'audi': 1, 'активно': 1, 'найбільший': 1, 'постачальник': 1, 'високотехнологічний': 1, 'продукція': 1, 'обладнання': 1, 'раз': 1, 'відзначити': 1, 'ефективність': 1, 'завдяки': 1, 'sap': 1, 'наприклад': 1, 'перший': 1, 'ввести': 1, 'почавши': 1, 'впроваджувати': 1, 'технологія': 1, 'додати': 1, 'співпрацювати': 1, 'галуза': 1, 'мостобудування': 1, 'енергоефективність': 1, 'муніципалітет': 1, 'підвищувати': 1, 'кваліфікація': 1, 'переймати': 1, 'досвід': 1, 'колега': 1, 'різний': 1, 'взяти': 1, 'відповідальність': 1, 'змінити': 1, 'могти': 1, 'нехаяти': 1, 'складно': 1, 'проблема': 1, 'вдаватися': 1, 'змінюватися': 1, 'розвиватися': 1, 'ставати': 1, 'красивіший': 1, 'комфортніший': 1, 'протяг': 1, 'останній': 1, 'четверо': 1, 'столичний': 1, 'влад': 1, 'оновлення': 1, 'інфраструктура': 1, 'будівництво': 1, 'новий': 1, 'школа': 1, 'садочок': 1, 'ремонт': 1, 'лікарня': 1, 'створення': 1, 'зелений': 1, 'зон': 1, 'відпочинок': 1, 'приїжджати': 1, 'мільйон': 1, 'турист': 1, 'проводити': 1, 'великий': 1, 'захід': 1, 'міжнародний': 1, 'образно': 1, 'назвати': 1, 'острів': 1, 'процвітання': 1, 'порівняти': 1, 'рок': 1, 'збільшитися': 1, 'удвічі': 1, 'зовнішній': 1, 'борг': 1, 'вдвічі': 1, 'скоротити': 1, 'українець': 1, 'жити': 1, 'оскільки': 1, 'найвищий': 1, 'заробітний': 1, 'плата': 1, 'безробіття': 1, 'кращий': 1, 'соціальний': 1, 'підтримка': 1, 'незахищений': 1, 'категорія': 1, 'населення': 1, 'аби': 1, 'київський': 1, 'стандарт': 1, 'ноу': 1, 'хау': 1, 'поширюватися': 1, 'амбітний': 1, 'план': 1, 'завдання': 1, 'процвітаючий': 1, 'задача': 1, 'продовжувати': 1, 'системний': 1, 'економічний': 1, 'реформа': 1, 'викорінювати': 1, 'корупція': 1, 'побороти': 1, 'жаль': 1, 'дивитися': 1, 'фото': 1, 'покликати': 1, 'повідомлятися': 1, 'берлін': 1, 'підписати': 1, 'меморандум': 1, 'atene': 1, 'kom': 1, 'gmbh': 1, 'співробітництво': 1, 'сфера': 1, 'стало': 1, 'відомо': 1, 'збільшити': 1, 'фінансування': 1, 'програма': 1, 'турбота': 1, 'назустріч': 1, 'киянин': 1, 'млрд': 1, 'повідомити': 1}

Тепер давайте зберемо всі "Body" до купи та знайдемо 10 слів, що найчастіше зустрічаються в корпусі. Корпус розглядаємо як збірник всіх "Body".

In [9]:
import collections 
allBodies = []
for i in range(0,1122):
    allBodies += dataset.iloc[i]["Body"]
topCountWords = dict(collections.Counter(allBodies).most_common(10))

print(topCountWords)

topCountWordsLst = list(topCountWords.keys())
print(topCountWordsLst)

{'україна': 1220, 'новий': 591, 'компанія': 590, 'корреспондент': 576, 'країна': 462, 'світ': 453, 'український': 448, 'повідомлятися': 433, 'перший': 432, 'канал': 400}
['україна', 'новий', 'компанія', 'корреспондент', 'країна', 'світ', 'український', 'повідомлятися', 'перший', 'канал']

Тепер давайте знайдемо значення TF для цих 10 слів.

In [10]:
def findTF():
    tfLst = []
    for wordId in range(0,len(topCountWordsLst)):
        tf = []
        for i in range(0,1122):
            if(topCountWordsLst[wordId] in wordCount(dataset.loc[i]["Body"]).keys()):
                numberInBody = wordCount(dataset.loc[i]["Body"])[topCountWordsLst[wordId]]
                totalNumberInBody = len(dataset.loc[i]["Body"])
                tfValue = numberInBody/totalNumberInBody
            else:
                tfValue = 0
            tf.append(tfValue)
        tfLst.append(tf)
    return tfLst 
tfLst = findTF()
tfLst = pd.DataFrame(tfLst).T
tfLst.columns = topCountWordsLst

tfLst.info()
tfLst.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   україна        1122 non-null   float64
 1   новий          1122 non-null   float64
 2   компанія       1122 non-null   float64
 3   корреспондент  1122 non-null   float64
 4   країна         1122 non-null   float64
 5   світ           1122 non-null   float64
 6   український    1122 non-null   float64
 7   повідомлятися  1122 non-null   float64
 8   перший         1122 non-null   float64
 9   канал          1122 non-null   float64
dtypes: float64(10)
memory usage: 87.8 KB

,україна,новий,компанія,корреспондент,країна,світ,український,повідомлятися,перший,канал
0,0.011364,0.002841,0.011364,0.000000,0.005682,0.000000,0.011364,0.002841,0.002841,0.000000
1,0.022989,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.019608,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.012500,0.000000,0.000000,0.000000,0.000000,0.000000,0.012500
5,0.009174,0.000000,0.009174,0.009174,0.000000,0.000000,0.000000,0.000000,0.000000,0.009174
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020833,0.020833,0.000000
8,0.000000,0.000000,0.000000,0.010989,0.000000,0.000000,0.000000,0.021978,0.000000,0.010989
9,0.000000,0.000000,0.000000,0.009434,0.000000,0.000000,0.009434,0.028302,0.009434,0.009434
10,0.000000,0.009434,0.000000,0.000000,0.000000,0.000000,0.000000,0.009434,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.009709,0.000000,0.000000,0.000000,0.000000,0.000000,0.009709
12,0.000000,0.000000,0.000000,0.008197,0.000000,0.000000,0.000000,0.008197,0.000000,0.008197
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.007194,0.000000,0.000000,0.007194,0.000000,0.007194,0.000000,0.007194,0.000000,0.000000

Знайдемо значення IDF для цих 10 слів.

In [11]:
def findIDF():
    idf = []
    for wordId in range(0,len(topCountWordsLst)):
        count = 0
        for i in range(0,1122):
            if(topCountWordsLst[wordId] in wordCount(dataset.loc[i]["Body"]).keys()):
                count += 1
        idf.append(np.log(1122/count))
    return idf 
idf = findIDF()
idf = pd.DataFrame(idf).T
idf.columns = topCountWordsLst

idfLst = list(idf.loc[0])
print(idfLst)

[1.0018447367331151, 1.3257745995772372, 1.505415189617934, 0.9091859062504104, 1.6522300579549787, 1.5339303599259553, 1.5256998607894396, 1.0774474774760665, 1.4699085011610242, 1.1312238742568705]

Тепер знайдемо значення TF-IDF.

In [12]:
def findTFIDF():
    tfIdf = []
    for i in range(0,1122):
        currTFIDF = []
        for j in range(0,10):
            currTFIDF.append(tfLst.loc[i][j]*idfLst[j])
        tfIdf.append(currTFIDF)
    return tfIdf

tfIdf = findTFIDF()
tfIdf = pd.DataFrame(tfIdf)
tfIdf.columns = topCountWordsLst
tfIdf.info()
tfIdf.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   україна        1122 non-null   float64
 1   новий          1122 non-null   float64
 2   компанія       1122 non-null   float64
 3   корреспондент  1122 non-null   float64
 4   країна         1122 non-null   float64
 5   світ           1122 non-null   float64
 6   український    1122 non-null   float64
 7   повідомлятися  1122 non-null   float64
 8   перший         1122 non-null   float64
 9   канал          1122 non-null   float64
dtypes: float64(10)
memory usage: 87.8 KB

,україна,новий,компанія,корреспондент,країна,світ,український,повідомлятися,перший,канал
0,0.011385,0.003766,0.017107,0.000000,0.009388,0.0,0.017337,0.003061,0.004176,0.000000
1,0.023031,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.021126,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.011365,0.000000,0.0,0.000000,0.000000,0.000000,0.014140
5,0.009191,0.000000,0.013811,0.008341,0.000000,0.0,0.000000,0.000000,0.000000,0.010378
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.022447,0.030623,0.000000
8,0.000000,0.000000,0.000000,0.009991,0.000000,0.0,0.000000,0.023680,0.000000,0.012431
9,0.000000,0.000000,0.000000,0.008577,0.000000,0.0,0.014393,0.030494,0.013867,0.010672

Тепер давайте створимо та наповнимо Bag of Word.

In [13]:
allUniqueWords = list(wordCount(allBodies).keys())
allCounts = []
for j in range(0,1122):
    allCounts.append(wordCount(dataset.loc[j]["Body"]))

def createBagOfWord():
    arrays = []
    for i in range(0,len(allUniqueWords)):
        arr = []
        word = allUniqueWords[i]
        for j in range(0,1122):
            if word in allCounts[j].keys():
                arr.append(allCounts[j][word])
            else:
                arr.append(0)
        arrays.append(arr)
    return arrays

bag = createBagOfWord()
bag = pd.DataFrame(bag).T
bag.columns = allUniqueWords
bag.info()
bag.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Columns: 23566 entries, україна to концертний
dtypes: int64(23566)
memory usage: 201.7 MB

,україна,новий,компанія,корреспондент,країна,світ,український,повідомлятися,перший,канал,...,ліон,фейхтвангер,луцілія,сенека,гернсбас,dolce,владивосток,суперсиметрія,кремлівський,концертний
0,4,1,4,0,2,0,4,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,1,0,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,1,0,0,0,2,0,1,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,1,0,0,1,3,1,1,...,0,0,0,0,0,0,0,0,0,0
10,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,1,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,1,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,3,0,0,1,1,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

Для перевірки давайте підрахуємо кількості слів в нашому першому записі та порівняємо з Bag of Word.

In [14]:
print(wordCount(dataset.loc[0]["Body"]))

{'кличко': 11, 'кий': 10, 'мер': 7, 'німецький': 7, 'місто': 6, 'інвестиція': 5, 'київ': 5, 'зазначити': 5, 'столиця': 5, 'перспективний': 4, 'ринок': 4, 'бізнес': 4, 'німеччина': 4, 'компанія': 4, 'український': 4, 'партнер': 4, 'україна': 4, 'відкритий': 3, 'віталій': 3, 'співпраця': 3, 'управління': 3, 'один': 3, 'європейський': 3, 'працювати': 3, 'робити': 3, 'економіка': 2, 'представник': 2, 'інвестор': 2, 'запевнити': 2, 'надійний': 2, 'хотіти': 2, 'розвиток': 2, 'основний': 2, 'підкреслити': 2, 'бюджет': 2, 'міський': 2, 'smart': 2, 'city': 2, 'фахівець': 2, 'рівня': 2, 'країна': 2, 'рівень': 2, 'заявити': 1, 'виступ': 1, 'дно': 1, 'цьогоріч': 1, 'проходити': 1, 'аахен': 1, 'інформувати': 1, 'прес': 1, 'служба': 1, 'четвер': 1, 'вересень': 1, 'головний': 1, 'тема': 1, 'форум': 1, 'світовий': 1, 'торгівля': 1, 'умова': 1, 'глобальний': 1, 'зміна': 1, 'він': 1, 'брати': 1, 'участь': 1, 'чоловік': 1, 'середа': 1, 'понад': 1, 'промислово': 1, 'торговельний': 1, 'палата': 1, 'провідний': 1, 'здійснювати': 1, 'зовнішньоторговельний': 1, 'діяльність': 1, 'експерт': 1, 'підготовлений': 1, 'інвестування': 1, 'іноземний': 1, 'приходити': 1, 'введений': 1, 'прозорий': 1, 'механізм': 1, 'гарант': 1, 'виступати': 1, 'особисто': 1, 'захисник': 1, 'говорити': 1, 'німецьки': 1, 'приречений': 1, 'ефективний': 1, 'налаштований': 1, 'звернутися': 1, 'пріоритетний': 1, 'напрямок': 1, 'відносини': 1, 'допомагати': 1, 'політично': 1, 'підтримувати': 1, 'прагнення': 1, 'зовнішньоекономічний': 1, 'відомий': 1, 'deutz': 1, 'fahr': 1, 'knauf': 1, 'hipp': 1, 'walter': 1, 'bau': 1, 'leon': 1, 'bmw': 1, 'man': 1, 'audi': 1, 'активно': 1, 'найбільший': 1, 'постачальник': 1, 'високотехнологічний': 1, 'продукція': 1, 'обладнання': 1, 'раз': 1, 'відзначити': 1, 'ефективність': 1, 'завдяки': 1, 'sap': 1, 'наприклад': 1, 'перший': 1, 'ввести': 1, 'почавши': 1, 'впроваджувати': 1, 'технологія': 1, 'додати': 1, 'співпрацювати': 1, 'галуза': 1, 'мостобудування': 1, 'енергоефективність': 1, 'муніципалітет': 1, 'підвищувати': 1, 'кваліфікація': 1, 'переймати': 1, 'досвід': 1, 'колега': 1, 'різний': 1, 'взяти': 1, 'відповідальність': 1, 'змінити': 1, 'могти': 1, 'нехаяти': 1, 'складно': 1, 'проблема': 1, 'вдаватися': 1, 'змінюватися': 1, 'розвиватися': 1, 'ставати': 1, 'красивіший': 1, 'комфортніший': 1, 'протяг': 1, 'останній': 1, 'четверо': 1, 'столичний': 1, 'влад': 1, 'оновлення': 1, 'інфраструктура': 1, 'будівництво': 1, 'новий': 1, 'школа': 1, 'садочок': 1, 'ремонт': 1, 'лікарня': 1, 'створення': 1, 'зелений': 1, 'зон': 1, 'відпочинок': 1, 'приїжджати': 1, 'мільйон': 1, 'турист': 1, 'проводити': 1, 'великий': 1, 'захід': 1, 'міжнародний': 1, 'образно': 1, 'назвати': 1, 'острів': 1, 'процвітання': 1, 'порівняти': 1, 'рок': 1, 'збільшитися': 1, 'удвічі': 1, 'зовнішній': 1, 'борг': 1, 'вдвічі': 1, 'скоротити': 1, 'українець': 1, 'жити': 1, 'оскільки': 1, 'найвищий': 1, 'заробітний': 1, 'плата': 1, 'безробіття': 1, 'кращий': 1, 'соціальний': 1, 'підтримка': 1, 'незахищений': 1, 'категорія': 1, 'населення': 1, 'аби': 1, 'київський': 1, 'стандарт': 1, 'ноу': 1, 'хау': 1, 'поширюватися': 1, 'амбітний': 1, 'план': 1, 'завдання': 1, 'процвітаючий': 1, 'задача': 1, 'продовжувати': 1, 'системний': 1, 'економічний': 1, 'реформа': 1, 'викорінювати': 1, 'корупція': 1, 'побороти': 1, 'жаль': 1, 'дивитися': 1, 'фото': 1, 'покликати': 1, 'повідомлятися': 1, 'берлін': 1, 'підписати': 1, 'меморандум': 1, 'atene': 1, 'kom': 1, 'gmbh': 1, 'співробітництво': 1, 'сфера': 1, 'стало': 1, 'відомо': 1, 'збільшити': 1, 'фінансування': 1, 'програма': 1, 'турбота': 1, 'назустріч': 1, 'киянин': 1, 'млрд': 1, 'повідомити': 1}

Як бачимо, підрахунки в нашому Baf of Word співпадають з підрахунками для окремого запису.